ALTER TABLE messages
ADD COLUMN IF NOT EXISTS is_system BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE messages
ADD COLUMN IF NOT EXISTS suggestion_type TEXT;

ALTER TABLE messages
ADD COLUMN IF NOT EXISTS attachment_url TEXT;
