ALTER TABLE users
ADD COLUMN IF NOT EXISTS balance INTEGER NOT NULL DEFAULT 0;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS referral_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS tier TEXT NOT NULL DEFAULT 'bronze';
